// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBBt2DkWCDgRQvjE76DoA1loSWZ192Rt4',
    appId: '1:552599057959:web:8cebaa23fdaa18da6f4002',
    messagingSenderId: '552599057959',
    projectId: 'foodfacil-ecb8c',
    authDomain: 'foodfacil-ecb8c.firebaseapp.com',
    storageBucket: 'foodfacil-ecb8c.appspot.com',
    measurementId: 'G-JVJV8MHN8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw2XsDp-WxC0SuTkivtZ3o9TQFREA8H38',
    appId: '1:552599057959:android:dfc812d7b5d60f316f4002',
    messagingSenderId: '552599057959',
    projectId: 'foodfacil-ecb8c',
    storageBucket: 'foodfacil-ecb8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUvIwoNcHQrZuXE8Tybr8njke_N65dX_w',
    appId: '1:552599057959:ios:7c166943c48823516f4002',
    messagingSenderId: '552599057959',
    projectId: 'foodfacil-ecb8c',
    storageBucket: 'foodfacil-ecb8c.appspot.com',
    iosBundleId: 'com.example.foodfacil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUvIwoNcHQrZuXE8Tybr8njke_N65dX_w',
    appId: '1:552599057959:ios:7c166943c48823516f4002',
    messagingSenderId: '552599057959',
    projectId: 'foodfacil-ecb8c',
    storageBucket: 'foodfacil-ecb8c.appspot.com',
    iosBundleId: 'com.example.foodfacil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBBt2DkWCDgRQvjE76DoA1loSWZ192Rt4',
    appId: '1:552599057959:web:aad709ecc43189446f4002',
    messagingSenderId: '552599057959',
    projectId: 'foodfacil-ecb8c',
    authDomain: 'foodfacil-ecb8c.firebaseapp.com',
    storageBucket: 'foodfacil-ecb8c.appspot.com',
    measurementId: 'G-W397L4GCDL',
  );
}
